export const products = [
  {
    product_name: "Wireless Mouse",
    category: "Electronics",
    price: 29.99,
    status: "active",
    created_date: "2023-05-21",
    description: "Pro",
  },
  {
    product_name: "Bluetooth Speaker",
    category: "Electronics",
    price: 49.99,
    status: "active",
    created_date: "2023-06-15",
    description: "High-quality sound",
  },
  {
    product_name: "Running Shoes",
    category: "Apparel",
    price: 75.0,
    status: "not_active",
    created_date: "2023-01-10",
    description: "Comfortable and lightweight",
  },
  {
    product_name: "Electric Toothbrush",
    category: "Health & Personal Care",
    price: 39.95,
    status: "active",
    created_date: "2023-02-25",
    description: "Advanced cleaning technology",
  },
  {
    product_name: "Yoga Mat",
    category: "Sports & Outdoors",
    price: 20.0,
    status: "not_active",
    created_date: "2022-11-30",
    description: "Eco-friendly material",
  },
  {
    product_name: "Smartphone",
    category: "Electronics",
    price: 699.0,
    status: "active",
    created_date: "2023-03-05",
    description: "High-performance device",
  },
  {
    product_name: "Laptop",
    category: "Computers",
    price: 999.99,
    status: "active",
    created_date: "2023-04-10",
    description: "Powerful processing and sleek design",
  },
  {
    product_name: "Coffee Maker",
    category: "Kitchen Appliances",
    price: 79.99,
    status: "not_active",
    created_date: "2022-12-20",
    description: "Makes delicious coffee",
  },
  {
    product_name: "Desk Lamp",
    category: "Home & Office",
    price: 24.99,
    status: "active",
    created_date: "2023-07-01",
    description: "Adjustable brightness",
  },
  {
    product_name: "Water Bottle",
    category: "Sports & Outdoors",
    price: 15.0,
    status: "active",
    created_date: "2023-08-18",
    description: "Leak-proof and durable",
  },
];
