export const products = [
  {
    product_name: "Wireless Mouse",
    category: "Electronics",
    price: 29.99,
    status: "active",
    created_date: "2023-05-21",
  },
  {
    product_name: "Bluetooth Speaker",
    category: "Electronics",
    price: 49.99,
    status: "active",
    created_date: "2023-06-15",
  },
  {
    product_name: "Running Shoes",
    category: "Apparel",
    price: 75.0,
    status: "not_active",
    created_date: "2023-01-10",
  },
  {
    product_name: "Electric Toothbrush",
    category: "Health & Personal Care",
    price: 39.95,
    status: "active",
    created_date: "2023-02-25",
  },
  {
    product_name: "Yoga Mat",
    category: "Sports & Outdoors",
    price: 20.0,
    status: "not_active",
    created_date: "2022-11-30",
  },
  {
    product_name: "Smartphone",
    category: "Electronics",
    price: 699.0,
    status: "active",
    created_date: "2023-03-05",
  },
  {
    product_name: "Laptop",
    category: "Computers",
    price: 999.99,
    status: "active",
    created_date: "2023-04-10",
  },
  {
    product_name: "Coffee Maker",
    category: "Kitchen Appliances",
    price: 79.99,
    status: "not_active",
    created_date: "2022-12-20",
  },
  {
    product_name: "Desk Lamp",
    category: "Home & Office",
    price: 24.99,
    status: "active",
    created_date: "2023-07-01",
  },
  {
    product_name: "Water Bottle",
    category: "Sports & Outdoors",
    price: 15.0,
    status: "active",
    created_date: "2023-08-18",
  },
];
